package com.wavesight.harbor.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Data implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Document")
	private com.wavesight.harbor.model.Document document;

	public Data() {
	}

	public com.wavesight.harbor.model.Document getDocument() {
		return this.document;
	}

	public void setDocument(com.wavesight.harbor.model.Document document) {
		this.document = document;
	}

	public Data(com.wavesight.harbor.model.Document document) {
		this.document = document;
	}

}