package com.wavesight.harbor.model;

/*Copyright ABS Nautical Systems 2002-2024*/

/*
Date                Author                  Changes
----------------    -------------------     -------------------
Oct 01, 2024        VPandita                 ADO-126833
*/

/***************************************************************/


/***************************************************************/

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Document")
@org.kie.api.remote.Remotable
public class Document implements java.io.Serializable
{

    static final long        serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Document ID")
    private java.lang.Long   id;
    @org.kie.api.definition.type.Label(value = "Context")
    private java.lang.String context;
    @org.kie.api.definition.type.Label(value = "Description")
    private java.lang.String description;

    public Document()
    {
    }

    public java.lang.Long getId()
    {
        return this.id;
    }

    public void setId(java.lang.Long id)
    {
        this.id = id;
    }

    public java.lang.String getContext()
    {
        return this.context;
    }

    public void setContext(java.lang.String context)
    {
        this.context = context;
    }

    public java.lang.String getDescription()
    {
        return this.description;
    }

    public void setDescription(java.lang.String description)
    {
        this.description = description;
    }

    public Document(java.lang.Long id, java.lang.String context, java.lang.String description)
    {
        this.id = id;
        this.context = context;
        this.description = description;
    }

    @Override
    public String toString()
    {
        return "Document [id=" + id + ", context=" + context + ", description=" + description + "]";
    }
}
