package com.wavesight.harbor.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Document")
@org.kie.api.remote.Remotable
public class Document implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Document ID")
	private java.lang.Long id;
	@org.kie.api.definition.type.Label("Concept Code")
	private java.lang.Long conceptCode;
	@org.kie.api.definition.type.Label("Concept Name")
	private java.lang.String conceptName;

	public Document() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getConceptCode() {
		return this.conceptCode;
	}

	public void setConceptCode(java.lang.Long conceptCode) {
		this.conceptCode = conceptCode;
	}

	public java.lang.String getConceptName() {
		return this.conceptName;
	}

	public void setConceptName(java.lang.String conceptName) {
		this.conceptName = conceptName;
	}

	public String toString() {
		return "DOCUMENT OBJ:" + this.id;
	}

	public Document(java.lang.Long id, java.lang.Long conceptCode,
			java.lang.String conceptName) {
		this.id = id;
		this.conceptCode = conceptCode;
		this.conceptName = conceptName;
	}

}