package com.abs.wsns_bpmn;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Error BO")
public class ErrorBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Error Code")
	private java.lang.Long errorCode;
	@org.kie.api.definition.type.Label(value = "Error Message")
	private java.lang.String error;
	@org.kie.api.definition.type.Label(value = "Error Stack Trace")
	private java.lang.String errorStackTrace;

	public ErrorBO() {
	}

	public java.lang.Long getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(java.lang.Long errorCode) {
		this.errorCode = errorCode;
	}

	public java.lang.String getError() {
		return this.error;
	}

	public void setError(java.lang.String error) {
		this.error = error;
	}

	public java.lang.String getErrorStackTrace() {
		return this.errorStackTrace;
	}

	public void setErrorStackTrace(java.lang.String errorStackTrace) {
		this.errorStackTrace = errorStackTrace;
	}

	public ErrorBO(java.lang.Long errorCode, java.lang.String error,
			java.lang.String errorStackTrace) {
		this.errorCode = errorCode;
		this.error = error;
		this.errorStackTrace = errorStackTrace;
	}

}